jk
import java.awt.*;
import java.awt.geom.Rectangle2D;
import java.util.logging.Level;
import java.util.logging.Logger;

public class frmDemoGraphics20 extends javax.swing.JFrame {

    Graphics g = null;
    Point p1 = null, p2 = null;
    Rectangle2D rect = new Rectangle2D.Double(100, 100, 60, 40);

    public frmDemoGraphics20() {
        initComponents();
    }
    public static int x = 0;
    public static boolean check = true;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        btnDraw = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lbResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnMainMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnMainMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnMainMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnMainLayout = new javax.swing.GroupLayout(pnMain);
        pnMain.setLayout(pnMainLayout);
        pnMainLayout.setHorizontalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnMainLayout.setVerticalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        btnDraw.setText("Draw");
        btnDraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrawActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        lbResult.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbResult.setForeground(new java.awt.Color(204, 0, 0));
        lbResult.setText("Result:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lbResult, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addComponent(btnDraw, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDraw)
                            .addComponent(btnClear)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lbResult, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(pnMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void btnDrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrawActionPerformed
        int w = pnMain.getWidth();
        int h = pnMain.getHeight();
        Thread tr = new Thread(new Runnable() {
            public void run() {
                do{
                    g = pnMain.getGraphics();
                    g.setColor(Color.red);
                    g.drawRect(0, 0, w / 2, h / 2);
                    g.setColor(Color.yellow);
                    g.fillOval(w / 2, h / 2, w / 4, h / 4);
                    g.setColor(Color.blue);
                    g.drawLine(10, 10, 100, 200);
                    Graphics2D g2 = (Graphics2D) g;
                    g2.fill(rect);
                    g.setColor(Color.blue);
                    g.drawRect(x + 20, 20, 100, 50);
                    g.setColor(Color.pink);
                    g.fillOval(x + 25, 60, 30, 30);
                    //g.setColor(Color.yellow);
                    g.fillOval(x + 80, 60, 30, 30);
                    try {
                        
                        g.setColor(pnMain.getBackground());
                        g.fillRect(0, 0, pnMain.getWidth(), pnMain.getHeight());
                        x = x + 10;
                        Thread.sleep(500);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(frmDemoGraphics20.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    if(check==false){
                     g.setColor(Color.blue);
                    g.drawRect(x + 20, 20, 100, 50);
                    g.setColor(Color.pink);
                    g.fillOval(x + 25, 60, 30, 30);
                    //g.setColor(Color.yellow);
                    g.fillOval(x + 80, 60, 30, 30);
                    }
                }while (check == true) ;
            }
        }
        );
        tr.start();

    }//GEN-LAST:event_btnDrawActionPerformed
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        check = false;
        g = pnMain.getGraphics();
        g.setColor(pnMain.getBackground());
        g.fillRect(0, 0, pnMain.getWidth(), pnMain.getHeight());
    }//GEN-LAST:event_btnClearActionPerformed
    private void pnMainMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMainMousePressed
        p1 = evt.getPoint();
    }//GEN-LAST:event_pnMainMousePressed
    private void pnMainMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMainMouseReleased
        p2 = evt.getPoint();
        g = pnMain.getGraphics();
        g.drawLine(p1.x, p1.y, p2.x, p2.y);
        g.drawOval(p1.x, p1.y, p2.x - p1.x, p2.y - p1.y);
    }//GEN-LAST:event_pnMainMouseReleased

    private void pnMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMainMouseClicked
      check = false;
        if (rect.contains(evt.getPoint())) {
            lbResult.setText("TRUNG roi!");
        } else {
            lbResult.setText("Truot hehe.");
        }

    }//GEN-LAST:event_pnMainMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDemoGraphics20.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDemoGraphics20.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDemoGraphics20.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDemoGraphics20.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDemoGraphics20().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDraw;
    private javax.swing.JLabel lbResult;
    private javax.swing.JPanel pnMain;
    // End of variables declaration//GEN-END:variables
}
